version: '3'

services:
  db:
    image: postgres:15
    container_name: sopchatbot_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER} #
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Reference the password from .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: sopchatbot_app
    command: gunicorn --bind 0.0.0.0:8000 sopchatbot.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/sopchatbot_db # Reference the password from .env

volumes:
  postgres_data: